/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybank;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.*;

/**
 *
 * @author APURAV SHARMA
 */
public class changepass1 extends javax.swing.JFrame {

    /**
     * Creates new form changepass
     */
    Connection con=null;
    Statement stmt = null; //USED FOR RUNNING COMMAND
    ResultSet rs = null,rg = null;  //USED FOR STORING THE RECORDS WHICH COMES FROM TABLE
    PreparedStatement stat;
    String phone,oldpass;
    int otp,acc;
    public changepass1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblheading = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblotp = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        btnconfirm = new java.awt.Button();
        txtpass = new javax.swing.JPasswordField();
        txtpass1 = new javax.swing.JPasswordField();
        lblacc = new javax.swing.JLabel();
        txtacc = new javax.swing.JTextField();
        btnotp = new java.awt.Button();
        txtotp = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHANGE PASSWORD");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 97, 141));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblheading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        lblheading.setForeground(new java.awt.Color(255, 255, 255));
        lblheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheading.setText("CHANGE PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblheading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblheading)
                .addGap(39, 39, 39))
        );

        jPanel2.setBackground(new java.awt.Color(175, 214, 241));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblotp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblotp.setText("ENTER OTP");

        lblpass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblpass.setText("NEW PASSWORD");

        lblpass1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblpass1.setText("CONFIRM PASSWORD");

        btnconfirm.setBackground(new java.awt.Color(31, 97, 141));
        btnconfirm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm.setLabel("CONFIRM");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });

        txtpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });

        txtpass1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpass1KeyPressed(evt);
            }
        });

        lblacc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblacc.setText("ENTER ACCOUNT NUMBER");

        txtacc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccKeyPressed(evt);
            }
        });

        btnotp.setBackground(new java.awt.Color(31, 97, 141));
        btnotp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnotp.setForeground(new java.awt.Color(255, 255, 255));
        btnotp.setLabel("GENERATE OTP");
        btnotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnotpActionPerformed(evt);
            }
        });

        txtotp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtotp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtotpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblotp)
                    .addComponent(lblpass1)
                    .addComponent(lblpass)
                    .addComponent(lblacc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpass)
                    .addComponent(txtpass1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtacc)
                    .addComponent(txtotp))
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(329, 329, 329))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblacc)
                    .addComponent(txtacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpass)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpass1)
                            .addComponent(txtpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblotp)
                        .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        if(txtacc.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changepass1.this, "Enter valid password.");
            txtacc.grabFocus();
            return;
        }
        else if(txtotp.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changepass1.this, "Enter valid password.");
            txtotp.grabFocus();
            return;
        }
        else if(txtpass.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changepass1.this, "Enter valid password.");
            txtpass.grabFocus();
            return;
        }
        else if(txtpass1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changepass1.this, "Enter valid password.");
            txtpass1.grabFocus();
            return;
        }
        else
        {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=BANK;integratedSecurity=true";
            String pass = txtpass.getText();
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(url);
                stmt = con.createStatement();
                rg = stmt.executeQuery("SELECT * FROM ACCOUNTS");
                while(rg.next())
                {
                    if(phone.equals(rg.getString("PHONE")))
                    {
                        oldpass = rg.getString("PASSWORD");
                    }
                }
            }
            catch(Exception m)
            {
                System.out.println(m.getMessage());
            }
            String pass1 = txtpass1.getText();
            if(otp == Integer.parseInt(txtotp.getText()))
                {
                    if((pass.equals(pass1)) && (oldpass == null ? (pass) != null : !oldpass.equals(pass)) && (oldpass == null ? (pass1) != null : !oldpass.equals(pass1)))
                       {
                           try
                           {
                                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                                con = DriverManager.getConnection(url);
                                stat = con.prepareStatement("UPDATE ACCOUNTS SET PASSWORD=? WHERE PHONE = ?");
                                stat.setString(1, pass1);
                                stat.setString(2, phone);
                                stat.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Password changed successfully !");
                                this.dispose();
                                new userlogin().setVisible(true);
                                con.close();
                           }
                           catch(Exception m)
                           {
                               System.out.println(m.getMessage());
                           }
                       }
                    else if(oldpass.equals(pass) || oldpass.equals(pass1))
                            {
                                JOptionPane.showMessageDialog(null,"OLD PASSWORD AND NEW PASSWORD CAN'T BE SAME !");
                                txtpass.setText("");
                                txtpass1.setText("");
                            }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Entered password isn't same !");
                        txtpass.setText("");
                        txtpass1.setText("");
                    }
                }
            else
            {
                JOptionPane.showMessageDialog(null, "INVALID OTP !");
                txtotp.setText("");
            }   
        }
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isWhitespace(c))
        {
            txtpass.setEditable(false);
            JOptionPane.showMessageDialog(null, "No spaces !");
            txtpass.setEditable(true);
        }
        else
        {
            txtpass.setEditable(true);
        }
        txtpass.setTransferHandler(null);
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtpass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass1KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isWhitespace(c))
        {
            txtpass1.setEditable(false);
            JOptionPane.showMessageDialog(null, "No spaces !");
            txtpass1.setEditable(true);
        }
        else
        {
            txtpass1.setEditable(true);
        }
        txtpass1.setTransferHandler(null);
    }//GEN-LAST:event_txtpass1KeyPressed

    private void btnotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnotpActionPerformed
        // TODO add your handling code here:
        if(txtacc.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changepass1.this, "Enter valid account number.");
            txtacc.grabFocus();
            return;
        }
        else
        {
        acc = Integer.parseInt(txtacc.getText());
        int count = 0;
        String url = "jdbc:sqlserver://localhost:1433;databaseName=BANK;integratedSecurity=true";
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM ACCNO");
            while(rs.next())
            {
            if(acc==rs.getInt("ACCOUNTNO"))
            {
                phone = rs.getString("PHONE");
                count++;
                Random rand = new Random();
                otp = rand.nextInt(999999);
                try 
                {
			// Construct data
			String apiKey = "apikey=" + "7OG1UqMorVE-ruQEkjc0RVRGqywGy4jtO3v1OTI8ai";
			String message = "&message=" + "Your OTP is "+otp;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + "91"+phone;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) 
                        {
				stringBuffer.append(line);
			}
			rd.close();
			JOptionPane.showMessageDialog(null, "OTP sent successfully to your registered mobile no.");
//                        JOptionPane.showMessageDialog(null, "OTP is "+otp);
			//return stringBuffer.toString();
		} 
                catch (Exception e) 
                {
			System.out.println("Error SMS "+e);
			//return "Error "+e;
		}
            }
           
        }
          if(count==0)
            {
                JOptionPane.showMessageDialog(null, "Entered account number doesn't matches !");
                txtacc.setText("");
            }   
        }
        catch(Exception m)
        {
            System.out.println(m.getMessage());
        }
                }
    }//GEN-LAST:event_btnotpActionPerformed

    private void txtaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtacc.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtacc.setEditable(true);
        }
        else
        {
            txtacc.setEditable(true);
        }
        txtacc.setTransferHandler(null);
    }//GEN-LAST:event_txtaccKeyPressed

    private void txtotpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotpKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtotp.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtotp.setEditable(true);
        }
        else
        {
            txtotp.setEditable(true);
        }
        txtotp.setTransferHandler(null);
    }//GEN-LAST:event_txtotpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepass1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnconfirm;
    private java.awt.Button btnotp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblacc;
    private javax.swing.JLabel lblheading;
    private javax.swing.JLabel lblotp;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtotp;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtpass1;
    // End of variables declaration//GEN-END:variables
}
