/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybank;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.*;

/**
 *
 * @author APURAV SHARMA
 */
public class changephone extends javax.swing.JFrame {

    /**
     * Creates new form changephone
     */
    Connection con=null;
    Statement stmt = null; //USED FOR RUNNING COMMAND
    ResultSet rs = null,rg = null;  //USED FOR STORING THE RECORDS WHICH COMES FROM TABLE
    PreparedStatement stat,stat2;
    int otp;
    public changephone() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblheading = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbloldphone = new javax.swing.JLabel();
        txtoldphone = new javax.swing.JTextField();
        newphone = new javax.swing.JLabel();
        txtnewphone = new javax.swing.JTextField();
        btnotp = new java.awt.Button();
        lblotp = new javax.swing.JLabel();
        txtotp = new javax.swing.JTextField();
        btnupdate = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UPDATE PHONE NO");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 97, 141));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblheading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        lblheading.setForeground(new java.awt.Color(255, 255, 255));
        lblheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheading.setText("UPDATE REGISTERED PHONE NUMBER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblheading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblheading)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(175, 214, 241));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbloldphone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbloldphone.setText("ENTER OLD PHONE NUMBER");

        txtoldphone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtoldphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtoldphoneKeyPressed(evt);
            }
        });

        newphone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        newphone.setText("ENTER NEW PHONE NUMBER");

        txtnewphone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtnewphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnewphoneKeyPressed(evt);
            }
        });

        btnotp.setBackground(new java.awt.Color(31, 97, 141));
        btnotp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnotp.setForeground(new java.awt.Color(255, 255, 255));
        btnotp.setLabel("GENERATE OTP");
        btnotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnotpActionPerformed(evt);
            }
        });

        lblotp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblotp.setText("ENTER OTP");

        txtotp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtotp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtotpKeyPressed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(31, 97, 141));
        btnupdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setLabel("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newphone)
                    .addComponent(lbloldphone)
                    .addComponent(lblotp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtoldphone)
                    .addComponent(txtnewphone)
                    .addComponent(txtotp, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbloldphone)
                    .addComponent(txtoldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newphone)
                    .addComponent(txtnewphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblotp)
                    .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnotpActionPerformed
        // TODO add your handling code here:
        if(txtnewphone.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changephone.this, "Enter valid new phone number !");
            txtnewphone.grabFocus();
            return;
        }
        else
        {
        Random rand = new Random();
        otp = rand.nextInt(999999);
        String phone = txtnewphone.getText();
        try 
                {
			// Construct data
			String apiKey = "apikey=" + "7OG1UqMorVE-ruQEkjc0RVRGqywGy4jtO3v1OTI8ai";
			String message = "&message=" + "Your OTP is "+otp;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + "91"+phone;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) 
                        {
				stringBuffer.append(line);
			}
			rd.close();
//			JOptionPane.showMessageDialog(null, "OTP is "+otp);
                        JOptionPane.showMessageDialog(null, "OTP sent successfully !");
			//return stringBuffer.toString();
		} 
                catch (Exception e) 
                {
			System.out.println("Error SMS "+e);
			//return "Error "+e;
		}
        }
    }//GEN-LAST:event_btnotpActionPerformed

    private void txtoldphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoldphoneKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtoldphone.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtoldphone.setEditable(true);
        }
        else
        {
            txtoldphone.setEditable(true);
        }
        txtoldphone.setTransferHandler(null);
    }//GEN-LAST:event_txtoldphoneKeyPressed

    private void txtnewphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewphoneKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtnewphone.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtnewphone.setEditable(true);
        }
        else
        {
            txtnewphone.setEditable(true);
        }
        txtnewphone.setTransferHandler(null);
    }//GEN-LAST:event_txtnewphoneKeyPressed

    private void txtotpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotpKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtotp.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtotp.setEditable(true);
        }
        else
        {
            txtotp.setEditable(true);
        }
        txtotp.setTransferHandler(null);
    }//GEN-LAST:event_txtotpKeyPressed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if(txtoldphone.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changephone.this, "Enter valid old phone number !");
            txtoldphone.grabFocus();
            return;
        }
        else if(txtnewphone.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changephone.this, "Enter valid new phone number !");
            txtnewphone.grabFocus();
            return;
        }
        else if(txtotp.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(changephone.this, "Enter valid OTP !");
            txtotp.grabFocus();
            return;
        }
        else
        {
            String oldphone = txtoldphone.getText();
            String newphone = txtnewphone.getText();
            String url = "jdbc:sqlserver://localhost:1433;databaseName=BANK;integratedSecurity=true";
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(url);
                stmt = con.createStatement();
                rg = stmt.executeQuery("SELECT * FROM ACCOUNTS");
                while(rg.next())
                {
                    if(newphone.equals(rg.getString("PHONE")))
                    {
                        JOptionPane.showMessageDialog(null, "Entered new phone number already exists !");
                        txtnewphone.setText("");
                    }
                }
            }
            catch(Exception m)
            {
                System.out.println(m.getMessage());
            }
            
            if(userlogin.phone.equals(oldphone) && (userlogin.phone == null ? (newphone) != null : !userlogin.phone.equals(newphone)))
            {
                if(otp==Integer.parseInt(txtotp.getText()))
                {
                    
                    try
                    {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        con = DriverManager.getConnection(url);
                        stat = con.prepareStatement("UPDATE ACCOUNTS SET PHONE=? WHERE USERNAME = ?");
                        stat2 = con.prepareStatement("UPDATE ACCNO SET PHONE=? WHERE ACCOUNTNO = ?");
                        stat.setString(1,newphone);
                        stat.setString(2,userlogin.user);
                        stat2.setString(1,newphone);
                        stat2.setInt(2,userlogin.account);
                        stat.executeUpdate();
                        stat2.executeUpdate();
                        JOptionPane.showMessageDialog(null, "PHONE NUMBER UPDATED !");
                        this.dispose();
                        new userlogin().setVisible(true);
                        con.close();
                    }
                    catch(Exception m)
                    {
                        System.out.println(m.getMessage());
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "INVALID OTP !");
                    txtotp.setText("");
                }
            }
            else if(oldphone.equals(newphone))
            {
                JOptionPane.showMessageDialog(null, "OLD PHONE NUMBER AND NEW PHONE NUMBER CAN'T BE SAME !");
                txtnewphone.setText("");
                txtoldphone.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "ENTERED PHONE NUMBER DOESN'T MATCHES!");
                txtoldphone.setText("");
            }
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changephone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnotp;
    private java.awt.Button btnupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblheading;
    private javax.swing.JLabel lbloldphone;
    private javax.swing.JLabel lblotp;
    private javax.swing.JLabel newphone;
    private javax.swing.JTextField txtnewphone;
    private javax.swing.JTextField txtoldphone;
    private javax.swing.JTextField txtotp;
    // End of variables declaration//GEN-END:variables
}
