/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybank;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.*;

/**
 *
 * @author APURAV SHARMA
 */
public class create1 extends javax.swing.JFrame {

    /**
     * Creates new form create
     */
    Connection con=null;
    Statement stmt = null; //USED FOR RUNNING COMMAND
    ResultSet rs = null,rg = null;  //USED FOR STORING THE RECORDS WHICH COMES FROM TABLE
    PreparedStatement stat,stat2,stat3; //IF YOU WANT TO USE RUNTIME ERROR
    public int otp;
    public create1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblotp = new javax.swing.JPanel();
        txtpass = new javax.swing.JPasswordField();
        txtfirstname = new javax.swing.JTextField();
        txtbalance = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        lblphoneno = new javax.swing.JLabel();
        btncreate = new java.awt.Button();
        lblpassword = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        lblfirstname = new javax.swing.JLabel();
        lblnote = new javax.swing.JLabel();
        lbluserid = new javax.swing.JLabel();
        lblbalance = new javax.swing.JLabel();
        txtsecondname = new javax.swing.JTextField();
        lblsecondname = new javax.swing.JLabel();
        txtuserid = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        btnotp = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        txtotp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CREATE ACCOUNT");
        setResizable(false);

        lblotp.setBackground(new java.awt.Color(175, 214, 241));
        lblotp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });

        txtfirstname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        txtfirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyPressed(evt);
            }
        });

        txtbalance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalanceActionPerformed(evt);
            }
        });
        txtbalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbalanceKeyPressed(evt);
            }
        });

        lblage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblage.setText("AGE");

        lblphoneno.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblphoneno.setText("PHONE NUMBER");

        btncreate.setActionCommand("create");
        btncreate.setBackground(new java.awt.Color(31, 97, 141));
        btncreate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(255, 255, 255));
        btncreate.setLabel("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblpassword.setText("PASSWORD");

        txtphoneno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });
        txtphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphonenoKeyPressed(evt);
            }
        });

        lblfirstname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblfirstname.setText("FIRST NAME");

        lblnote.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblnote.setText("(MUST BE MORE THAN 10000)");

        lbluserid.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbluserid.setText("USER ID");

        lblbalance.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblbalance.setText("BALANCE");

        txtsecondname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtsecondname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsecondnameActionPerformed(evt);
            }
        });
        txtsecondname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsecondnameKeyPressed(evt);
            }
        });

        lblsecondname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblsecondname.setText("LAST NAME");

        txtuserid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuseridActionPerformed(evt);
            }
        });
        txtuserid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuseridKeyPressed(evt);
            }
        });

        txtage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });

        btnotp.setBackground(new java.awt.Color(31, 97, 141));
        btnotp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnotp.setForeground(new java.awt.Color(255, 255, 255));
        btnotp.setLabel("GENERATE OTP");
        btnotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnotpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("ENTER OTP");

        txtotp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtotp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtotpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout lblotpLayout = new javax.swing.GroupLayout(lblotp);
        lblotp.setLayout(lblotpLayout);
        lblotpLayout.setHorizontalGroup(
            lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblotpLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblotpLayout.createSequentialGroup()
                        .addComponent(lblnote, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblotpLayout.createSequentialGroup()
                        .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblotpLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lblotpLayout.createSequentialGroup()
                                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lblotpLayout.createSequentialGroup()
                                        .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblsecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblotpLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblotpLayout.createSequentialGroup()
                                                .addComponent(lblphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(144, 144, 144))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblotpLayout.createSequentialGroup()
                                                .addComponent(lbluserid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(236, 236, 236))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblotpLayout.createSequentialGroup()
                                                .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(197, 197, 197)))))
                                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(109, 109, 109))))
            .addGroup(lblotpLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        lblotpLayout.setVerticalGroup(
            lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblotpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblage)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfirstname)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsecondname)
                    .addComponent(txtsecondname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphoneno)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserid)
                    .addComponent(txtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbalance)
                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnote)
                .addGap(18, 18, 18)
                .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(lblotpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtotp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(207, 506));

        lblback.setIcon(new javax.swing.ImageIcon("C:\\Users\\APURAV SHARMA\\Desktop\\Bank Photos\\create+cross+new+plus+icon-1320168707626274697.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblback)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblback)
                .addGap(180, 180, 180))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblotp, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblotp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuseridActionPerformed

    private void txtsecondnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsecondnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsecondnameActionPerformed

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        if(txtage.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid age.");
            txtage.grabFocus();
            return;
        }
        else if(txtfirstname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid first name.");
            txtfirstname.grabFocus();
            return;
        }
        else if(txtsecondname.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid second name.");
            txtsecondname.grabFocus();
            return;
        }
        else if(txtphoneno.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid phone no.");
            txtphoneno.grabFocus();
            return;
        }
        else if(txtuserid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid user id.");
            txtuserid.grabFocus();
            return;
        }
        else if(txtpass.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid password.");
            txtpass.grabFocus();
            return;
        }
        else if(txtbalance.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid balance.");
            txtbalance.grabFocus();
            return;
        }
        else if(txtotp.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(create1.this, "Enter valid OTP.");
            txtotp.grabFocus();
            return;
        }
        else
        {
            
            String username = txtuserid.getText();
            int age = Integer.parseInt(txtage.getText());
            String firstname = txtfirstname.getText();
            String secondname = txtsecondname.getText();
            String phone = txtphoneno.getText();
            int balance = Integer.parseInt(txtbalance.getText());
            int count = 0;
            String url = "jdbc:sqlserver://localhost:1433;databaseName=BANK;integratedSecurity=true";
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(url);
                stmt = con.createStatement();
                rg = stmt.executeQuery("SELECT * FROM ACCOUNTS");
                while(rg.next())
                {
                    if(phone.equals(rg.getString("PHONE")))
                    {
                        JOptionPane.showMessageDialog(null, "Entered phone number already exists !");
                        txtphoneno.setText("");
                    }
                }
            }
            catch(Exception m)
            {
                System.out.println(m.getMessage());
            }
            for(int i = 0; i < phone.length(); i++)
            {
                    if(phone.charAt(i) != ' ')
                    count++;
            }
            if(otp==Integer.parseInt(txtotp.getText()))
            {
            if(age>18)
            {
            if(count==10)
            {
            if(balance > 10000)
            {
            
            try
            {
                Random rand = new Random();
                int accno = rand.nextInt(999999);
                
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(url);
                stat = con.prepareStatement("INSERT INTO ACCOUNTS VALUES(?,?,?,?,?,?,?)");
                stat2 = con.prepareStatement("INSERT INTO ACCNO VALUES(?,?)");
                String sql = "CREATE TABLE " +username+
                   "(DATE DATE, " +
                   " TYPE VARCHAR(20), " + 
                   " SECPERSON INT, " + 
                   " AMOUNT INT)"; 
                stmt = con.createStatement();
                rs = stmt.executeQuery("SELECT * FROM ACCOUNTS");
                while(rs.next())
                { 
                    if(username.equals(rs.getString("USERNAME")))
                    {
                        JOptionPane.showMessageDialog(create1.this, "This username has already been taken !");
                        txtuserid.setText("");
                    }
                }
                String pass = txtpass.getText();
                stat.setInt(1,age);
                stat.setString(2,firstname);
                stat.setString(3,secondname);
                stat.setString(4,phone);
                stat.setString(5,username);
                stat.setString(6,pass);
                stat.setInt(7,balance);
                stat2.setString(1,phone);
                stat2.setInt(2,accno);
                stmt.executeUpdate(sql);
                stat2.executeUpdate();
                stat.executeUpdate();
                this.dispose();
                con.close();
//                JOptionPane.showMessageDialog(null, "Your new account number is "+accno+".");
                try {
			// Construct data
			String apiKey = "apikey=" + "7OG1UqMorVE-ruQEkjc0RVRGqywGy4jtO3v1OTI8ai";
			String message = "&message=" + "Hey ! Your account number is "+accno;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + phone;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) {
				stringBuffer.append(line);
			}
			rd.close();
			JOptionPane.showMessageDialog(null, "Account number sent to your registered mobile number.");
//                        JOptionPane.showMessageDialog(null, "Account Number is "+accno+".");
//			return stringBuffer.toString();
		} catch (Exception e) {
			System.out.println("Error SMS "+e);
//			return "Error "+e;
		}
            }
            catch(Exception m)
            {
                System.out.println("Error !");
                System.out.println(m.getMessage());
            }
        }
            else
            {
                JOptionPane.showMessageDialog(null, "BALANCE SHOULD BE MORE THAN 10000RS !");
                txtbalance.setText("");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "ENTER 10 DIGIT VALID PHONE NUMBER ! !");
                txtphoneno.setText("");
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "MINIMUM AGE REQUIREMENET IS 18 !");
                txtage.setText("");
            }
        }
            else
            {
                JOptionPane.showMessageDialog(null, "INVALID OTP !");
                txtotp.setText("");
            }
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void txtbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalanceActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtage.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtage.setEditable(true);
        }
        else
        {
            txtage.setEditable(true);
        }
        txtage.setTransferHandler(null);
    }//GEN-LAST:event_txtageKeyPressed

    private void txtphonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphonenoKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtphoneno.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtphoneno.setEditable(true);
        }
        else
        {
            txtphoneno.setEditable(true);
        }
        txtphoneno.setTransferHandler(null);
    }//GEN-LAST:event_txtphonenoKeyPressed

    private void txtbalanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbalanceKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtbalance.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtbalance.setEditable(true);
        }
        else
        {
            txtbalance.setEditable(true);
        }
        txtbalance.setTransferHandler(null);
    }//GEN-LAST:event_txtbalanceKeyPressed

    private void txtfirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtfirstname.setEditable(true);
            
        }
        else
        {
            txtfirstname.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter alphabets !");
            txtfirstname.setEditable(true);
        }
        txtfirstname.setTransferHandler(null);
    }//GEN-LAST:event_txtfirstnameKeyPressed

    private void txtsecondnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecondnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtsecondname.setEditable(true);
            
        }
        else
        {
            txtsecondname.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter alphabets !");
            txtsecondname.setEditable(true);
        }
        txtsecondname.setTransferHandler(null);
    }//GEN-LAST:event_txtsecondnameKeyPressed

    private void txtuseridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuseridKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isWhitespace(c))
        {
            txtuserid.setEditable(false);
            JOptionPane.showMessageDialog(null, "No spaces !");
            txtuserid.setEditable(true);
        }
        else
        {
            txtuserid.setEditable(true);
        }
        txtuserid.setTransferHandler(null);
    }//GEN-LAST:event_txtuseridKeyPressed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isWhitespace(c))
        {
            txtpass.setEditable(false);
            JOptionPane.showMessageDialog(null, "No spaces !");
            txtpass.setEditable(true);
        }
        else
        {
            txtpass.setEditable(true);
        }
        txtpass.setTransferHandler(null);
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtotpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotpKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtotp.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtotp.setEditable(true);
        }
        else
        {
            txtotp.setEditable(true);
        }
        txtotp.setTransferHandler(null);
    }//GEN-LAST:event_txtotpKeyPressed

    private void btnotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnotpActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        otp = rand.nextInt(999999);
        String phone = txtphoneno.getText();
        try 
                {
			// Construct data
			String apiKey = "apikey=" + "7OG1UqMorVE-ruQEkjc0RVRGqywGy4jtO3v1OTI8ai";
			String message = "&message=" + "Your OTP is "+otp;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + "91"+phone;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) 
                        {
				stringBuffer.append(line);
			}
			rd.close();
//			JOptionPane.showMessageDialog(null, "OTP is "+otp);
                        JOptionPane.showMessageDialog(null, "OTP sent successfully !");
			//return stringBuffer.toString();
		} 
                catch (Exception e) 
                {
			System.out.println("Error SMS "+e);
			//return "Error "+e;
		}
    }//GEN-LAST:event_btnotpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btncreate;
    private java.awt.Button btnotp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblnote;
    private javax.swing.JPanel lblotp;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblsecondname;
    private javax.swing.JLabel lbluserid;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtotp;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtsecondname;
    private javax.swing.JTextField txtuserid;
    // End of variables declaration//GEN-END:variables
}