/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybank;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.*;
/**
 *
 * @author APURAV SHARMA
 */
public class delete extends javax.swing.JFrame {

    /**
     * Creates new form delete
     */
    Connection con=null;
    Statement stmt = null; //USED FOR RUNNING COMMAND
    ResultSet rs = null,rg = null;
    int otp;//USED FOR STORING THE RECORDS WHICH COMES FROM TABLE
    PreparedStatement stat,stat2,stat3; //IF YOU WANT TO USE RUNTIME ERROR
    public delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblage = new javax.swing.JLabel();
        txtuserid = new javax.swing.JTextField();
        txtacc = new javax.swing.JTextField();
        lblpass = new javax.swing.JLabel();
        lbluserid = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        btndelete = new java.awt.Button();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        lblotp = new javax.swing.JLabel();
        txtotp = new javax.swing.JTextField();
        btnotp = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DELETE ACCOUNT");

        jPanel1.setBackground(new java.awt.Color(175, 214, 241));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblage.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblage.setText("ACCOUNT NUMBER");

        txtuserid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuseridActionPerformed(evt);
            }
        });
        txtuserid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuseridKeyPressed(evt);
            }
        });

        txtacc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccActionPerformed(evt);
            }
        });
        txtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccKeyPressed(evt);
            }
        });

        lblpass.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblpass.setText("PASSWORD");

        lbluserid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbluserid.setText("USER ID");

        txtpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });

        btndelete.setActionCommand("delete");
        btndelete.setBackground(new java.awt.Color(31, 97, 141));
        btndelete.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setLabel("DELETE");
        btndelete.setPreferredSize(new java.awt.Dimension(99, 40));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        lblphone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblphone.setText("PHONE NUMBER ");

        txtphone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });

        lblotp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblotp.setText("ENTER OTP");

        txtotp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotpActionPerformed(evt);
            }
        });
        txtotp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtotpKeyPressed(evt);
            }
        });

        btnotp.setBackground(new java.awt.Color(31, 97, 141));
        btnotp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnotp.setForeground(new java.awt.Color(255, 255, 255));
        btnotp.setLabel("GENERATE OTP");
        btnotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnotpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblage)
                            .addComponent(lbluserid)
                            .addComponent(lblpass)
                            .addComponent(lblphone)
                            .addComponent(lblotp))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtuserid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtacc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtphone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtotp, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblage)
                    .addComponent(txtacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserid)
                    .addComponent(txtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpass)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnotp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblotp))
                .addGap(23, 23, 23)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\APURAV SHARMA\\Desktop\\Bank Photos\\61848.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccActionPerformed

    private void txtuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuseridActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(txtacc.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid account no.");
            txtacc.grabFocus();
            return;
        }
        else if(txtuserid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid username.");
            txtuserid.grabFocus();
            return;
        }
        else if(txtpass.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid password.");
            txtpass.grabFocus();
            return;
        }
        else if(txtotp.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid OTP.");
            txtotp.grabFocus();
            return;
        }
        else
        {
            int input = JOptionPane.showConfirmDialog(null, "Are you confirm you wish to delete the account ?");
            if (Integer.parseInt(txtotp.getText())==otp)
            {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=BANK;integratedSecurity=true";
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
                con = DriverManager.getConnection(url);
                int count = 0,balance;
                String phone = txtphone.getText();
                String username = txtuserid.getText();
                String pass = txtpass.getText();
                int acc;
//                int acc = Integer.parseInt(txtacc.getText());
                if(input == 0)
                {
                stmt = con.createStatement();  
                rs = stmt.executeQuery("SELECT * FROM ACCOUNTS");
                while (rs.next())
                {
                    if(username.equals(rs.getString("USERNAME")))
                    {
                        count++;
                        if(pass.equals(rs.getString("PASSWORD")))
                        {
                            if(phone.equals(rs.getString("PHONE")))
                            {
                                balance = rs.getInt("BALANCE");
                                if(balance<=1500)
                                {
                                rg = stmt.executeQuery("SELECT * FROM ACCNO");
                                while(rg.next())
                                {
                                if(phone.equals(rg.getString("PHONE")))
                                {
                                    acc = rg.getInt("ACCOUNTNO");
                                    if(acc==Integer.parseInt(txtacc.getText()))
                                            {  
                                stat = con.prepareStatement("DELETE FROM ACCOUNTS WHERE USERNAME = ? AND PASSWORD = ? AND PHONE = ?");
                                stat2 = con.prepareStatement("DELETE FROM ACCNO WHERE PHONE = ?");
                                stat3 = con.prepareStatement("DROP TABLE "+username);
                                stat.setString(1, username);
                                stat.setString(2, pass);
                                stat.setString(3, phone);
                                stat2.setString(1, phone);
                                stat.executeUpdate();
                                stat2.executeUpdate();
                                stat3.executeUpdate();
                                this.dispose();
                                break;
                                            
                                            }
                                    else
                                    {
                                         JOptionPane.showMessageDialog(null, "Incorrect account number !");
                                         txtacc.setText("");
                                         break;
                                    }
                                }
                                else
                            {
                                JOptionPane.showMessageDialog(null, "Incorrect Phone Number !");
                                txtphone.setText("");
                                break;
                            }
                            }
                            }
                                
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Your request doesn't meet minimum balance requirement. Please withdraw the remaining amount to proceed.");
                                    txtacc.setText("");
                                    txtuserid.setText("");
                                    txtpass.setText("");
                                    txtphone.setText("");
                                    txtotp.setText("");
                                    break;
                                }
                        }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Incorrect Phone Number !");
                                txtphone.setText("");
                                break;
                            }
                        }
                        else
                            {
                                JOptionPane.showMessageDialog(null, "Incorrect Password !");
                                txtpass.setText("");
                                break;
                            }
                    } 
                }
                if (count==0)
                    {
                        JOptionPane.showMessageDialog(null, "USER ID DOES NOT EXISTS !");
                        txtuserid.setText("");
                    }
                }
                else if(input==1)
                {
                txtacc.setText("");
                txtuserid.setText("");
                txtpass.setText("");
                txtphone.setText("");
                }
                else
                {
                this.dispose();
                }
                con.close();
            }
            catch(Exception m)
            {
                System.out.println(m.getMessage());
            }
            }  
            else
                {
                    JOptionPane.showMessageDialog(null, "Wrong OTP entered !");
                    this.dispose();
                }
        }
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotpActionPerformed

    private void btnotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnotpActionPerformed
        // TODO add your handling code here:
        if(txtacc.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid account no.");
            txtacc.grabFocus();
            return;
        }
        else if(txtuserid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid username.");
            txtuserid.grabFocus();
            return;
        }
        else if(txtpass.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid password.");
            txtpass.grabFocus();
            return;
        }
        else if(txtphone.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(delete.this, "Enter valid phone number.");
            txtphone.grabFocus();
            return;
        }
        else
        {
        Random rand = new Random();
        otp = rand.nextInt(999999);
        String phone = txtphone.getText();
        try 
                {
			// Construct data
			String apiKey = "apikey=" + "7OG1UqMorVE-ruQEkjc0RVRGqywGy4jtO3v1OTI8ai";
			String message = "&message=" + "Your OTP is "+otp;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + "91"+phone;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) 
                        {
				stringBuffer.append(line);
			}
			rd.close();
//			JOptionPane.showMessageDialog(null, "OTP sent successfully.");
                        JOptionPane.showMessageDialog(null, "OTP is "+otp);
			//return stringBuffer.toString();
		} 
                catch (Exception e) 
                {
			System.out.println("Error SMS "+e);
			//return "Error "+e;
		}
                }
    }//GEN-LAST:event_btnotpActionPerformed

    private void txtaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtacc.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtacc.setEditable(true);
        }
        else
        {
            txtacc.setEditable(true);
        }
    }//GEN-LAST:event_txtaccKeyPressed

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtphone.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtphone.setEditable(true);
        }
        else
        {
            txtphone.setEditable(true);
        }
    }//GEN-LAST:event_txtphoneKeyPressed

    private void txtuseridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuseridKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isWhitespace(c))
        {
            txtuserid.setEditable(false);
            JOptionPane.showMessageDialog(null, "No spaces !");
            txtuserid.setEditable(true);
        }
        else
        {
            txtuserid.setEditable(true);
        }
    }//GEN-LAST:event_txtuseridKeyPressed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isWhitespace(c))
        {
            txtpass.setEditable(false);
            JOptionPane.showMessageDialog(null, "No spaces !");
            txtpass.setEditable(true);
        }
        else
        {
            txtpass.setEditable(true);
        }
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtotpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotpKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {
            txtotp.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numeric value and no spaces!");
            txtotp.setEditable(true);
        }
        else
        {
            txtotp.setEditable(true);
        }
    }//GEN-LAST:event_txtotpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btndelete;
    private java.awt.Button btnotp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblotp;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lbluserid;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtotp;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtuserid;
    // End of variables declaration//GEN-END:variables
}
